/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export const projectModel = {
  languages: {
    enUS: {
      codename: 'en-US',
      name: 'English (United States)',
    },
    esES: {
      codename: 'es-ES',
      name: 'Spanish (Spain)',
    },
  },
  contentTypes: {
    about_us: {
      codename: 'about_us',
      name: 'About us',
      elements: {
        facts: {
          codename: 'facts',
          name: 'Facts',
        },
        url_pattern: {
          codename: 'url_pattern',
          name: 'URL pattern',
        },
        metadata__meta_title: {
          codename: 'metadata__meta_title',
          name: 'Meta title',
        },
        metadata__meta_description: {
          codename: 'metadata__meta_description',
          name: 'Meta description',
        },
        metadata__og_title: {
          codename: 'metadata__og_title',
          name: 'og:title',
        },
        metadata__og_description: {
          codename: 'metadata__og_description',
          name: 'og:description',
        },
        metadata__og_image: {
          codename: 'metadata__og_image',
          name: 'og:image',
        },
        metadata__twitter_site: {
          codename: 'metadata__twitter_site',
          name: 'twitter:site',
        },
        metadata__twitter_creator: {
          codename: 'metadata__twitter_creator',
          name: 'twitter:creator',
        },
        metadata__twitter_title: {
          codename: 'metadata__twitter_title',
          name: 'twitter:title',
        },
        metadata__twitter_description: {
          codename: 'metadata__twitter_description',
          name: 'twitter:description',
        },
        metadata__twitter_image: {
          codename: 'metadata__twitter_image',
          name: 'twitter:image',
        },
      },
    },
    accessory: {
      codename: 'accessory',
      name: 'Accessory',
      elements: {
        product_name: {
          codename: 'product_name',
          name: 'Product name',
        },
        price: {
          codename: 'price',
          name: 'Price',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        manufacturer: {
          codename: 'manufacturer',
          name: 'Manufacturer',
        },
        product_status: {
          codename: 'product_status',
          name: 'Product status',
        },
        short_description: {
          codename: 'short_description',
          name: 'Short description',
        },
        long_description: {
          codename: 'long_description',
          name: 'Long description',
        },
        url_pattern: {
          codename: 'url_pattern',
          name: 'URL pattern',
        },
        metadata__meta_title: {
          codename: 'metadata__meta_title',
          name: 'Meta title',
        },
        metadata__meta_description: {
          codename: 'metadata__meta_description',
          name: 'Meta description',
        },
        metadata__og_title: {
          codename: 'metadata__og_title',
          name: 'og:title',
        },
        metadata__og_description: {
          codename: 'metadata__og_description',
          name: 'og:description',
        },
        metadata__og_image: {
          codename: 'metadata__og_image',
          name: 'og:image',
        },
        metadata__twitter_site: {
          codename: 'metadata__twitter_site',
          name: 'twitter:site',
        },
        metadata__twitter_creator: {
          codename: 'metadata__twitter_creator',
          name: 'twitter:creator',
        },
        metadata__twitter_title: {
          codename: 'metadata__twitter_title',
          name: 'twitter:title',
        },
        metadata__twitter_description: {
          codename: 'metadata__twitter_description',
          name: 'twitter:description',
        },
        metadata__twitter_image: {
          codename: 'metadata__twitter_image',
          name: 'twitter:image',
        },
      },
    },
    article: {
      codename: 'article',
      name: 'Article',
      elements: {
        personas: {
          codename: 'personas',
          name: 'Personas',
        },
        title: {
          codename: 'title',
          name: 'Title',
        },
        teaser_image: {
          codename: 'teaser_image',
          name: 'Teaser image',
        },
        post_date: {
          codename: 'post_date',
          name: 'Post date',
        },
        summary: {
          codename: 'summary',
          name: 'Summary',
        },
        body_copy: {
          codename: 'body_copy',
          name: 'Body Copy',
        },
        related_articles: {
          codename: 'related_articles',
          name: 'Related articles',
        },
        meta_keywords: {
          codename: 'meta_keywords',
          name: 'Meta keywords',
        },
        meta_description: {
          codename: 'meta_description',
          name: 'Meta description',
        },
        url_pattern: {
          codename: 'url_pattern',
          name: 'URL pattern',
        },
        metadata__meta_title: {
          codename: 'metadata__meta_title',
          name: 'Meta title',
        },
        metadata__meta_description: {
          codename: 'metadata__meta_description',
          name: 'Meta description',
        },
        metadata__og_title: {
          codename: 'metadata__og_title',
          name: 'og:title',
        },
        metadata__og_description: {
          codename: 'metadata__og_description',
          name: 'og:description',
        },
        metadata__og_image: {
          codename: 'metadata__og_image',
          name: 'og:image',
        },
        metadata__twitter_site: {
          codename: 'metadata__twitter_site',
          name: 'twitter:site',
        },
        metadata__twitter_creator: {
          codename: 'metadata__twitter_creator',
          name: 'twitter:creator',
        },
        metadata__twitter_title: {
          codename: 'metadata__twitter_title',
          name: 'twitter:title',
        },
        metadata__twitter_description: {
          codename: 'metadata__twitter_description',
          name: 'twitter:description',
        },
        metadata__twitter_image: {
          codename: 'metadata__twitter_image',
          name: 'twitter:image',
        },
      },
    },
    brewer: {
      codename: 'brewer',
      name: 'Brewer',
      elements: {
        product_name: {
          codename: 'product_name',
          name: 'Product name',
        },
        price: {
          codename: 'price',
          name: 'Price',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        product_status: {
          codename: 'product_status',
          name: 'Product status',
        },
        short_description: {
          codename: 'short_description',
          name: 'Short description',
        },
        long_description: {
          codename: 'long_description',
          name: 'Long description',
        },
        url_pattern: {
          codename: 'url_pattern',
          name: 'URL pattern',
        },
        manufacturer: {
          codename: 'manufacturer',
          name: 'Manufacturer',
        },
        metadata__meta_title: {
          codename: 'metadata__meta_title',
          name: 'Meta title',
        },
        metadata__meta_description: {
          codename: 'metadata__meta_description',
          name: 'Meta description',
        },
        metadata__og_title: {
          codename: 'metadata__og_title',
          name: 'og:title',
        },
        metadata__og_description: {
          codename: 'metadata__og_description',
          name: 'og:description',
        },
        metadata__og_image: {
          codename: 'metadata__og_image',
          name: 'og:image',
        },
        metadata__twitter_site: {
          codename: 'metadata__twitter_site',
          name: 'twitter:site',
        },
        metadata__twitter_creator: {
          codename: 'metadata__twitter_creator',
          name: 'twitter:creator',
        },
        metadata__twitter_title: {
          codename: 'metadata__twitter_title',
          name: 'twitter:title',
        },
        metadata__twitter_description: {
          codename: 'metadata__twitter_description',
          name: 'twitter:description',
        },
        metadata__twitter_image: {
          codename: 'metadata__twitter_image',
          name: 'twitter:image',
        },
      },
    },
    cafe: {
      codename: 'cafe',
      name: 'Cafe',
      elements: {
        street: {
          codename: 'street',
          name: 'Street',
        },
        city: {
          codename: 'city',
          name: 'City',
        },
        country: {
          codename: 'country',
          name: 'Country',
        },
        state: {
          codename: 'state',
          name: 'State',
        },
        zip_code: {
          codename: 'zip_code',
          name: 'ZIP Code',
        },
        phone: {
          codename: 'phone',
          name: 'Phone',
        },
        email: {
          codename: 'email',
          name: 'Email',
        },
        photo: {
          codename: 'photo',
          name: 'Photo',
        },
      },
    },
    coffee: {
      codename: 'coffee',
      name: 'Coffee',
      elements: {
        product_name: {
          codename: 'product_name',
          name: 'Product name',
        },
        price: {
          codename: 'price',
          name: 'Price',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        short_description: {
          codename: 'short_description',
          name: 'Short description',
        },
        long_description: {
          codename: 'long_description',
          name: 'Long description',
        },
        product_status: {
          codename: 'product_status',
          name: 'Product status',
        },
        farm: {
          codename: 'farm',
          name: 'Farm',
        },
        country: {
          codename: 'country',
          name: 'Country',
        },
        variety: {
          codename: 'variety',
          name: 'Variety',
        },
        altitude: {
          codename: 'altitude',
          name: 'Altitude',
        },
        url_pattern: {
          codename: 'url_pattern',
          name: 'URL pattern',
        },
        processing: {
          codename: 'processing',
          name: 'Processing',
        },
        metadata__meta_title: {
          codename: 'metadata__meta_title',
          name: 'Meta title',
        },
        metadata__meta_description: {
          codename: 'metadata__meta_description',
          name: 'Meta description',
        },
        metadata__og_title: {
          codename: 'metadata__og_title',
          name: 'og:title',
        },
        metadata__og_description: {
          codename: 'metadata__og_description',
          name: 'og:description',
        },
        metadata__og_image: {
          codename: 'metadata__og_image',
          name: 'og:image',
        },
        metadata__twitter_site: {
          codename: 'metadata__twitter_site',
          name: 'twitter:site',
        },
        metadata__twitter_creator: {
          codename: 'metadata__twitter_creator',
          name: 'twitter:creator',
        },
        metadata__twitter_title: {
          codename: 'metadata__twitter_title',
          name: 'twitter:title',
        },
        metadata__twitter_description: {
          codename: 'metadata__twitter_description',
          name: 'twitter:description',
        },
        metadata__twitter_image: {
          codename: 'metadata__twitter_image',
          name: 'twitter:image',
        },
      },
    },
    fact_about_us: {
      codename: 'fact_about_us',
      name: 'Fact about us',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        description: {
          codename: 'description',
          name: 'Description',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
      },
    },
    grinder: {
      codename: 'grinder',
      name: 'Grinder',
      elements: {
        product_name: {
          codename: 'product_name',
          name: 'Product name',
        },
        price: {
          codename: 'price',
          name: 'Price',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        manufacturer: {
          codename: 'manufacturer',
          name: 'Manufacturer',
        },
        product_status: {
          codename: 'product_status',
          name: 'Product status',
        },
        short_description: {
          codename: 'short_description',
          name: 'Short description',
        },
        long_description: {
          codename: 'long_description',
          name: 'Long description',
        },
        url_pattern: {
          codename: 'url_pattern',
          name: 'URL pattern',
        },
        metadata__meta_title: {
          codename: 'metadata__meta_title',
          name: 'Meta title',
        },
        metadata__meta_description: {
          codename: 'metadata__meta_description',
          name: 'Meta description',
        },
        metadata__og_title: {
          codename: 'metadata__og_title',
          name: 'og:title',
        },
        metadata__og_description: {
          codename: 'metadata__og_description',
          name: 'og:description',
        },
        metadata__og_image: {
          codename: 'metadata__og_image',
          name: 'og:image',
        },
        metadata__twitter_site: {
          codename: 'metadata__twitter_site',
          name: 'twitter:site',
        },
        metadata__twitter_creator: {
          codename: 'metadata__twitter_creator',
          name: 'twitter:creator',
        },
        metadata__twitter_title: {
          codename: 'metadata__twitter_title',
          name: 'twitter:title',
        },
        metadata__twitter_description: {
          codename: 'metadata__twitter_description',
          name: 'twitter:description',
        },
        metadata__twitter_image: {
          codename: 'metadata__twitter_image',
          name: 'twitter:image',
        },
      },
    },
    hero_unit: {
      codename: 'hero_unit',
      name: 'Hero Unit',
      elements: {
        title: {
          codename: 'title',
          name: 'Title',
        },
        image: {
          codename: 'image',
          name: 'Image',
        },
        marketing_message: {
          codename: 'marketing_message',
          name: 'Marketing message',
        },
      },
    },
    home: {
      codename: 'home',
      name: 'Home',
      elements: {
        hero_unit: {
          codename: 'hero_unit',
          name: 'Hero unit',
        },
        articles: {
          codename: 'articles',
          name: 'Articles',
        },
        our_story: {
          codename: 'our_story',
          name: 'Our story',
        },
        cafes: {
          codename: 'cafes',
          name: 'Cafes',
        },
        contact: {
          codename: 'contact',
          name: 'Contact',
        },
        url_pattern: {
          codename: 'url_pattern',
          name: 'URL pattern',
        },
        metadata__meta_title: {
          codename: 'metadata__meta_title',
          name: 'Meta title',
        },
        metadata__meta_description: {
          codename: 'metadata__meta_description',
          name: 'Meta description',
        },
        metadata__og_title: {
          codename: 'metadata__og_title',
          name: 'og:title',
        },
        metadata__og_description: {
          codename: 'metadata__og_description',
          name: 'og:description',
        },
        metadata__og_image: {
          codename: 'metadata__og_image',
          name: 'og:image',
        },
        metadata__twitter_site: {
          codename: 'metadata__twitter_site',
          name: 'twitter:site',
        },
        metadata__twitter_creator: {
          codename: 'metadata__twitter_creator',
          name: 'twitter:creator',
        },
        metadata__twitter_title: {
          codename: 'metadata__twitter_title',
          name: 'twitter:title',
        },
        metadata__twitter_description: {
          codename: 'metadata__twitter_description',
          name: 'twitter:description',
        },
        metadata__twitter_image: {
          codename: 'metadata__twitter_image',
          name: 'twitter:image',
        },
      },
    },
    hosted_video: {
      codename: 'hosted_video',
      name: 'Hosted video',
      elements: {
        video_id: {
          codename: 'video_id',
          name: 'Video ID',
        },
        video_host: {
          codename: 'video_host',
          name: 'Video host',
        },
      },
    },
    office: {
      codename: 'office',
      name: 'Office',
      elements: {
        name: {
          codename: 'name',
          name: 'Name',
        },
        street: {
          codename: 'street',
          name: 'Street',
        },
        city: {
          codename: 'city',
          name: 'City',
        },
        country: {
          codename: 'country',
          name: 'Country',
        },
        state: {
          codename: 'state',
          name: 'State',
        },
        zip_code: {
          codename: 'zip_code',
          name: 'Zip code',
        },
        phone: {
          codename: 'phone',
          name: 'Phone',
        },
        email: {
          codename: 'email',
          name: 'Email',
        },
      },
    },
    tweet: {
      codename: 'tweet',
      name: 'Tweet',
      elements: {
        tweet_link: {
          codename: 'tweet_link',
          name: 'Tweet link',
        },
        theme: {
          codename: 'theme',
          name: 'Theme',
        },
        display_options: {
          codename: 'display_options',
          name: 'Display options',
        },
      },
    },
  },
  taxonomies: {
    manufacturer: {
      codename: 'manufacturer',
      name: 'Manufacturer',
      terms: {
        aerobie: {
          codename: 'aerobie',
          name: 'Aerobie',
          terms: {},
        },
        chemex: {
          codename: 'chemex',
          name: 'Chemex',
          terms: {},
        },
        espro: {
          codename: 'espro',
          name: 'Espro',
          terms: {},
        },
        hario: {
          codename: 'hario',
          name: 'Hario',
          terms: {},
        },
      },
    },
    personas: {
      codename: 'personas',
      name: 'Personas',
      terms: {
        coffee_expert: {
          codename: 'coffee_expert',
          name: 'Coffee expert',
          terms: {
            barista: {
              codename: 'barista',
              name: 'Barista',
              terms: {},
            },
            cafe_owner: {
              codename: 'cafe_owner',
              name: 'Cafe owner',
              terms: {},
            },
          },
        },
        coffee_enthusiast: {
          codename: 'coffee_enthusiast',
          name: 'Coffee enthusiast',
          terms: {
            coffee_lover: {
              codename: 'coffee_lover',
              name: 'Coffee lover',
              terms: {},
            },
            coffee_blogger: {
              codename: 'coffee_blogger',
              name: 'Coffee blogger',
              terms: {},
            },
          },
        },
      },
    },
    processing: {
      codename: 'processing',
      name: 'Processing',
      terms: {
        wet__washed_: {
          codename: 'wet__washed_',
          name: 'Wet (Washed)',
          terms: {},
        },
        dry__natural_: {
          codename: 'dry__natural_',
          name: 'Dry (Natural)',
          terms: {},
        },
        semi_dry: {
          codename: 'semi_dry',
          name: 'Semi-dry',
          terms: {},
        },
      },
    },
    product_status: {
      codename: 'product_status',
      name: 'Product status',
      terms: {
        on_sale: {
          codename: 'on_sale',
          name: 'On sale',
          terms: {},
        },
        bestseller: {
          codename: 'bestseller',
          name: 'Bestseller',
          terms: {},
        },
      },
    },
  },
};
