import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type AboutUs = IContentItem<{
  facts: Elements.LinkedItemsElement<IContentItem>;
  urlPattern: Elements.UrlSlugElement;
  metadataMetaTitle: Elements.TextElement;
  metadataMetaDescription: Elements.TextElement;
  metadataOgTitle: Elements.TextElement;
  metadataOgDescription: Elements.TextElement;
  metadataOgImage: Elements.AssetsElement;
  metadataTwitterSite: Elements.TextElement;
  metadataTwitterCreator: Elements.TextElement;
  metadataTwitterTitle: Elements.TextElement;
  metadataTwitterDescription: Elements.TextElement;
  metadataTwitterImage: Elements.AssetsElement;
}>;
