import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type Cafe = IContentItem<{
  street: Elements.TextElement;
  city: Elements.TextElement;
  country: Elements.TextElement;
  state: Elements.TextElement;
  zipCode: Elements.TextElement;
  phone: Elements.TextElement;
  email: Elements.TextElement;
  photo: Elements.AssetsElement;
}>;
