import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type Coffee = IContentItem<{
  productName: Elements.TextElement;
  price: Elements.NumberElement;
  image: Elements.AssetsElement;
  shortDescription: Elements.RichTextElement;
  longDescription: Elements.RichTextElement;
  productStatus: Elements.TaxonomyElement;
  farm: Elements.TextElement;
  country: Elements.TextElement;
  variety: Elements.TextElement;
  altitude: Elements.TextElement;
  urlPattern: Elements.UrlSlugElement;
  processing: Elements.TaxonomyElement;
  metadataMetaTitle: Elements.TextElement;
  metadataMetaDescription: Elements.TextElement;
  metadataOgTitle: Elements.TextElement;
  metadataOgDescription: Elements.TextElement;
  metadataOgImage: Elements.AssetsElement;
  metadataTwitterSite: Elements.TextElement;
  metadataTwitterCreator: Elements.TextElement;
  metadataTwitterTitle: Elements.TextElement;
  metadataTwitterDescription: Elements.TextElement;
  metadataTwitterImage: Elements.AssetsElement;
}>;
