import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type FactAboutUs = IContentItem<{
  title: Elements.TextElement;
  description: Elements.RichTextElement;
  image: Elements.AssetsElement;
}>;
