import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type HeroUnit = IContentItem<{
  title: Elements.TextElement;
  image: Elements.AssetsElement;
  marketingMessage: Elements.RichTextElement;
}>;
