import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type Home = IContentItem<{
  heroUnit: Elements.LinkedItemsElement<IContentItem>;
  articles: Elements.LinkedItemsElement<IContentItem>;
  ourStory: Elements.LinkedItemsElement<IContentItem>;
  cafes: Elements.LinkedItemsElement<IContentItem>;
  contact: Elements.RichTextElement;
  urlPattern: Elements.UrlSlugElement;
  metadataMetaTitle: Elements.TextElement;
  metadataMetaDescription: Elements.TextElement;
  metadataOgTitle: Elements.TextElement;
  metadataOgDescription: Elements.TextElement;
  metadataOgImage: Elements.AssetsElement;
  metadataTwitterSite: Elements.TextElement;
  metadataTwitterCreator: Elements.TextElement;
  metadataTwitterTitle: Elements.TextElement;
  metadataTwitterDescription: Elements.TextElement;
  metadataTwitterImage: Elements.AssetsElement;
}>;
