import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type HostedVideo = IContentItem<{
  videoId: Elements.TextElement;
  videoHost: Elements.MultipleChoiceElement;
}>;
