import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0'
 */
export type Tweet = IContentItem<{
  tweetLink: Elements.TextElement;
  theme: Elements.MultipleChoiceElement;
  displayOptions: Elements.MultipleChoiceElement;
}>;
